.TH CLIENT 1 "Sept 2025" "v0.4.1" "User Commands"
.SH NAME
client \- simple client application using myutils
.SH SYNOPSIS
.B client
.RI [ options ] " " [ file... ]
.SH DESCRIPTION
The client program demonstrates string and file utilities provided by the myutils library.
It accepts files or options and prints results to standard output.
.SH OPTIONS
.TP
.B -h, --help
Show help information.
.TP
.B -v, --version
Print version information.
.SH AUTHOR
Zeenat Fatima <zeenat71@example.com>
