.TH MYCAT 1 "September 2025" "v0.4.1" "User Commands"
.SH NAME
mycat \- prints the contents of a file to standard output
.SH SYNOPSIS
.B mycat
.RI [ filename ... ]
.SH DESCRIPTION
The
.B mycat
command reads each file in sequence and writes it to standard output.
.SH AUTHOR
Zeenat Fatima <your-email@example.com>
