.TH MYSTRLEN 3 "Sept 2025" "v0.4.1" "Library Functions"
.SH NAME
mystrlen \- return the length of a C string
.SH SYNOPSIS
.B int mystrlen(const char *s)
.SH DESCRIPTION
Counts characters in the C string pointed to by s up to but not including the terminating NUL ('\0').
Returns the number of characters.
.SH AUTHOR
Zeenat Fatima <zeenat71@example.com>
