install:
	sudo cp client /usr/local/bin/                    # Copy executable
	sudo mkdir -p /usr/local/share/man/man3/         # Ensure man3 folder exists
	sudo cp man/man3/mycat.1 /usr/local/share/man/man3/  # Copy man page
	sudo mandb                                      # Update man page database
